# Scanners are applied in the order they are listed here.

input_scanners:
  Anonymize:
    # allowed_names: []
    # hidden_names: []
    # entity_types: []
    # preamble: ""
    use_faker: false
  BanSubstrings:
    substrings: ["test"]
    match_type: "word"
    case_sensitive: false
    redact: false
    contains_all: false
  BanTopics:
    topics: ["violence"]
    threshold: 0.6
  Code:
    # allowed: []
    denied: ["go"]
  Language:
    valid_languages: [ "en" ]
  PromptInjection:
    threshold: 0.9
  Regex:
    # good_patterns: [""]
    bad_patterns: [ "Bearer [A-Za-z0-9-._~+/]+" ]
  Secrets:
    redact_mode: "all"
  Sentiment:
    # lexicon="vader_lexicon"
    threshold: -0.1
  TokenLimit:
    limit: 4096
    encoding_name: "cl100k_base"
  Toxicity:
    threshold: 0.7


output_scanners:
  BanSubstrings:
    match_type: "word"
    case_sensitive: false
    substrings: ["test"]
    redact: false
    contains_all: false
  BanTopics:
    threshold: 0.6
    topics: ["violence"]
  Bias:
    threshold: 0.75
  Code:
    #allowed: ["python"]
    denied: ["python"]
  Deanonymize:
    matching_strategy: "exact"
  FactualConsistency:
    minimum_score: 0.5
  JSON:
    required_elements: 0
    repair: true
  Language:
    valid_languages: [ "en" ]
  LanguageSame:
  MaliciousURLs:
    threshold: 0.75
  NoRefusal:
    threshold: 0.5
  Regex:
    # good_patterns: [""]
    bad_patterns: ["Bearer [A-Za-z0-9-._~+/]+"]
  Relevance:
    threshold: 0.5
  Sensitive:
    # entity_types:
    redact: false
    threshold: 0.0
  Sentiment:
    threshold: -0.1
    # lexicon: "vader_lexicon"
  Toxicity:
    threshold: 0.7
