name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - "docs/**"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt -r requirements-dev.txt
      - name: Download spacy dictionary
        run: |
          python -m spacy download en_core_web_trf
      - name: Test with pytest
        run: |
          python -m pytest --exitfirst --verbose --failed-first --cov=.
